### ISSUE TITLE
[jcertif] Unable to Load User Issue

### ISSUE THREAD

**Issue by aboarken** [joomla/certification.joomla.org#9]
Based on the below picture, its seems that some admin users who have created Joomlers Certifications Profiles in Joomla Certification Site have been deleted. A profile has been accessed and its showing the following warning message: Warning JUser: :_load: Unable to load user with ID: 411.

![Deleted User](https://user-images.githubusercontent.com/18500882/153769955-3d80cc91-dfe3-4c0a-9fe1-a8501ee9a892.png)

**Comment by JeroenMoolenschot** [comment]
Thanks for reporting this. Problem is solved now.

**Comment by aboarken** [comment]
Thanks @Joomill
